version: "2"
linters:
  disable:
    - errcheck
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
issues:
  max-issues-per-linter: 0
  max-same-issues: 0