database:
  dsn: "postgres://skimatik:skimatik_test_password@localhost:5432/skimatik_test?sslmode=disable"
  schema: "public"

output:
  directory: "./test-output"
  package: "repositories"

# Generate all functions by default
default_functions: "all"

tables:
  users:
  posts:
  comments:
    functions: ["create", "delete", "paginate"]  # Override for specific table 