name: Sync Documentation to Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout wiki repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy documentation files to wiki
        run: |
          # Remove existing files (except .git)
          find wiki/ -name "*.md" -delete
          
          # Copy all markdown files from docs/ to wiki/
          cp docs/*.md wiki/
          
          # List files for verification
          ls -la wiki/

      - name: Commit and push to wiki
        run: |
          cd wiki
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-sync documentation from main repository

            Updated: $(date -u +'%Y-%m-%d %H:%M:%S UTC')
            Source: ${{ github.sha }}"
            git push origin master
          fi 